version: '2'

services:
  web:
    build: web/
    restart: always
    volumes:
      - ./web/public_html:/var/www/html
      - ./web/log:/var/log/apache2
    ports:
      - "80:80"
    networks:
      - docker_lamp
    depends_on:
      - db
  db:
    build: mysql/
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/script:/usr/local/src
      - ./mysql/log:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Str0ngPassw0rd
      MYSQL_DATABASE: websitedb
      MYSQL_USER: websiteuser
      MYSQL_PASSWORD: wStr0ngPassw0rd
    networks:
      - docker_lamp

networks:
  docker_lamp:
    driver: bridge
